name: Compare Maven Dependencies

on:
  push:
    branches:
      - main

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sandbox Repo
        uses: actions/checkout@v4

      - name: Checkout Prod Repo
        uses: actions/checkout@v4
        with:
          repository: adityajain773568-commits/unity-prod
          path: prod
          token: ${{ secrets.MY_PAT}}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run Comparison
        run: java ComparePom.java
