name: Compare Maven Dependencies

on:
  push:
    branches:
      - main

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sandbox Repo
        uses: actions/checkout@v4

      - name: Checkout Prod Repo
        uses: actions/checkout@v4
        with:
          repository: adityajain773568-commits/unity-prod
          path: prod

      - name: Verify files
        run: |
          echo "Sandbox:"
          ls -la
          echo ""
          echo "Prod:"
          ls -la prod

      - name: Compare pom.xml files
        shell: bash
        run: |
          echo "Comparing pom.xml files..."

          if diff pom.xml prod/pom.xml > diff.txt; then
            echo "✅ No differences found."
          else
            echo "❌ Differences found:"
            cat diff.txt
            exit 1
          fi
